# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeneralUserGO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeneralUserGO

	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'Fabric'
	pod 'Crashlytics'



  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'GeneralUserGOTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GeneralUserGO-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeneralUserGO-tvOS

  target 'GeneralUserGO-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
