# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'generaluser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for generaluser

	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
 
  target 'generaluserTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'generaluser-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for generaluser-tvOS

  target 'generaluser-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
