# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeneralUserGO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeneralUserGO

	pod 'Firebase/Core', '~> 5.19.0'
  pod 'Firebase/Messaging', '~> 5.19.0'
	pod 'Fabric'
	pod 'Crashlytics'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  target 'GeneralUserGOTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'GeneralUserGO-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeneralUserGO-tvOS

  target 'GeneralUserGO-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
